
name: run-publisher-with-env

on:
  workflow_call:
    inputs:
      API_MANAGEMENT_ENVIRONMENT: 
        required: true
        type: string    
      COMMIT_ID:
        required: false
        type: string       
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: 
        required: true
        type: string          
    secrets:
      AZURE_RESOURCE_GROUP_NAME:
        required: true
      API_MANAGEMENT_SERVICE_NAME: 
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true   
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.API_MANAGEMENT_ENVIRONMENT }}    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish-toolkit.yaml
          name: toolkit
          
      - name: Run publisher with Config Yaml
        if: ${{ inputs.CONFIGURATION_YAML_PATH != '' }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          chmod +x ./publisher
          ./publisher             
