name: Run - Extractor

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  extract:
    runs-on: ubuntu-latest
    environment: Dev # change this to match the dev environment created in settings 
    steps:
      - uses: actions/checkout@v3
          
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish-toolkit.yaml
          name: toolkit

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run extractor
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
        run: |
          ls
          chmod +x ${{ GITHUB.WORKSPACE }}/ArmTemplates
          ${{ GITHUB.WORKSPACE }}/ArmTemplates extract --extractorConfig ../extract.dev.json

      - name: publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-from-portal
          path: ${{ GITHUB.WORKSPACE }}/apimartifacts

  create-pull-request:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Download artifacts-from-portal
        uses: actions/download-artifact@v2
        with:
          name: artifacts-from-portal
          path: "${{ GITHUB.WORKSPACE }}/apimartifacts"

      - name: Create artifacts pull request
        uses: peter-evans/create-pull-request@v3
        env:
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts  # change this to the artifacts folder          
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "updated extract from apim instance ${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }}"
          title: "${{ env.API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH }} - extract"
          body: >
            This PR is auto-generated by Github actions workflow
          labels: extract, automated pr
